---
title: "Model"
author: "Bernadette Stadler"
date: "11/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fs)
library(janitor)
library(tidyverse)

```

```{r read in data}
model_data <- read_csv("raw-data/womens-football-2019-clean.csv", 
                  col_types = cols(
                    X1 = col_character(),
                    Population = col_number(),
                    `Global Gender Gap Ranking 2018` = col_character(),
                    `FIFA WF Ranking 2019` = col_character(),
                    `Female players playing organized football` = col_character(),
                    `licesned coaches` = col_character(),
                    `licensed referees` = col_character(),
                    `Women's soccer strategy?` = col_character(),
                    `Mixed-gender football?` = col_character()
)) %>% clean_names() 


# read in fifa data, clean names 

unzip("raw-data/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_511444.zip")

# unzip world bank data file 

file_move("API_NY.GDP.MKTP.CD_DS2_en_csv_v2_511444.csv", "raw-data/GDP_data.csv")

# move file of interest to raw-data and rename it to something less clunky 

file_copy("raw-data/GDP_data.csv", "State-of-womens-soccer/raw-data/GDP_data.csv", overwrite =  TRUE)

# copy the file into the app 

file_delete("Metadata_Country_API_NY.GDP.MKTP.CD_DS2_en_csv_v2_511444.csv")

file_delete("Metadata_Indicator_API_NY.GDP.MKTP.CD_DS2_en_csv_v2_511444.csv")

# delete extra files 

gdp_data <- suppressWarnings(read_csv("raw-data/GDP_data.csv", skip =4, 
                     col_types = cols(
  .default = col_double(),
  `Country Name` = col_character(),
  `Country Code` = col_character(),
  `Indicator Name` = col_character(),
  `Indicator Code` = col_character(),
  `2019` = col_logical(),
  X65 = col_logical()
))) %>% clean_names()

# read in data, using suppress warnings to suppress a warning about a column with a 
# missing name being named 

gender_index <- read_csv("raw-data/data.csv", 
         col_types = cols(
  `Country ISO3` = col_character(),
  `Country Name` = col_character(),
  `Indicator Id` = col_double(),
  Indicator = col_character(),
  `Subindicator Type` = col_character(),
  `2006` = col_double(),
  `2007` = col_double(),
  `2008` = col_double(),
  `2009` = col_double(),
  `2010` = col_double(),
  `2011` = col_double(),
  `2012` = col_double(),
  `2013` = col_double(),
  `2014` = col_double(),
  `2015` = col_double(),
  `2016` = col_double(),
  `2018` = col_double()
)) %>% clean_names()

```

```{r prep data for regression}
model_data2 <- model_data %>%
  mutate(gendergap_18 = suppressWarnings(as.numeric((global_gender_gap_ranking_2018)))) %>%
  
  # mutate fifa data to change the name of global_gender_gap_ranking_2018 to something 
  # easier to use and also to make it numeric. I used suppress warnings here to quiet 
  # the NA introduced by coercion warning 
  
  mutate(fifa_19 = suppressWarnings(as.numeric((fifa_wf_ranking_2019)))) %>%
  
  # make fifa_19, same logic as above 
  
  mutate(fem_players = suppressWarnings(
    as.numeric((female_players_playing_organized_football)))) %>%
  
  # make fem_players, same logic as above
  
  select(x1, population, gendergap_18, fifa_19, fem_players) %>% 
  
  # select variables of interest 
  
  drop_na(gendergap_18)

  # drop NAs in gendergap_18. I didn't drop all NAs because it decimated the dataset,
  # but wanted to drop NAs from the variable that I will join by 

gdp_clean <- gdp_data %>% select(country_name, indicator_name, x2018)

  # select variables of interst in gdp data 
  

gender_index_clean <- gender_index %>%
  select(country_name, indicator, subindicator_type, x2018) %>%
  filter(indicator == "Overall Global Gender Gap Index" & subindicator_type == "Rank")

  # select columns and rows of interest from global gender gap data 

merge_1 <- gdp_clean %>%
  left_join(gender_index_clean, by = "country_name") %>%
  mutate(GDP = x2018.x) %>%
  mutate(gender_rank = x2018.y) %>%
  select(country_name, GDP, gender_rank)

  # join gdp and gender gap data 

merge_2 <- model_data2 %>% left_join(merge_1, by = c("gendergap_18" = "gender_rank")) %>%
  
  # join merged data above with fifa data 
  
  mutate(GDP = log10(GDP)) %>% 
  mutate(population = log10(population))

  # take log of GDP and population so the graph won't look so crazy  
  
```

```{r ggplot}

ggplot(merge_2, aes(x = GDP, y = fifa_19)) +
  
  # make a ggplot. This is where I will add interactive elements in shiny. 
  
  geom_point() +
  
  # add points 
  
  geom_smooth(formula = y ~ x, method = "lm")

  # add regression 

```

