---
title: "National teams worldwide"
author: "Bernadette Stadler"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(readr)

```

```{r}
wws <- read_csv("raw-data/tabula-GSSS 2017.csv", col_types = cols(
  league = col_character(),
  country = col_character(),
  Season = col_character(),
  Sport = col_character(),
  Teams = col_double(),
  Players = col_double()
))%>% clean_names()

mws <- read_csv("raw-data/tabula-GSSS 2017_2.csv", col_types =cols(
  RANK = col_character(),
  TEAM = col_character(),
  LEAGUE = col_character()
)) %>% drop_na() %>% filter(!LEAGUE == "LEAGUE") %>% clean_names()

mws_18 <- read_csv("raw-data/tabula-GSSS 2018.csv", col_types =cols(
  COUNTRY = col_character(),
  CONTINENT = col_character(),
  X4 = col_character()
)) %>% clean_names()

```

```{r}
mws2 <- mws %>% filter(league == "EPL" | league == "Bundesliga" | league == "Ligue 1" | league == "La Liga" | league == "Serie A" | league == "MLS" | league == "CSL" | league == "Scot Prem" | league == "J.League") %>% 
  mutate(Country = case_when(league == "EPL" ~ "England", 
                             league == "Bundesliga" ~ "Germany", 
                             league == "Serie A" ~ "Italy", 
                             league == "Ligue 1" ~ "France", 
                             league == "La Liga" ~ "Spain", 
                             league == "MLS" ~ "USA", 
                             league == "CSL" ~ "China", 
                             league == "Scot Prem" ~ "Scotland", 
                             league == "J.League" ~ "Japan", 
                             TRUE ~ "NA"
                             )) %>% 
  select(league, avg_annual_pay_2, Country) %>% 
  mutate(avg_annual_pay_2 = if_else(avg_annual_pay_2 == "$6,739,250($129,601)", "$6,739,250 ($129,601)", avg_annual_pay_2)) %>% 
  separate(avg_annual_pay_2, into = c("annual_pay"), sep = " ") %>% 
  mutate(annual_pay = parse_number(annual_pay))

country_number <- mws2 %>% count(Country)

mws3 <- country_number %>% right_join(mws2, by = "Country") %>% 
  group_by(Country) %>% 
  mutate(avg_annual_pay_country = sum(annual_pay)/n) %>% 
  group_by(Country, avg_annual_pay_country) %>% 
  count() %>% 
  mutate(year = 2017)

missing_countries <- mws_18 %>% select(country, avg_basic_annual_1) %>% 
  drop_na() %>% 
  filter(country %in% c("AUSTRALIA ASIA", "MEXICO", "SWEDEN EUROPE")) %>%
  mutate(year = 2018) %>% 
  mutate(Country = country) %>% 
  mutate(avg_annual_pay_country = parse_number(avg_basic_annual_1)) %>% 
  select(Country, avg_annual_pay_country, year)
  

mws4 <- mws3 %>% bind_rows(missing_countries) %>% 
  mutate(country_clean = case_when(Country == "AUSTRALIA ASIA" ~ "Australia", 
                             Country == "SWEDEN EUROPE" ~ "Sweden", 
                             Country == "MEXICO" ~ "Mexico", 
                             TRUE ~ Country)) %>% 
  mutate(Gender = "M")

wws2 <- wws %>% filter(sport == "Football") %>% select(u_s, country) %>% 
  mutate(avg_salary = parse_number(u_s)) %>%
  mutate(Gender = "W") %>% 
  mutate(year = 2017)

graph_data <- wws2 %>% full_join(mws4, by = c("avg_salary" = "avg_annual_pay_country", "country" = "country_clean", "Gender" = "Gender", "year" = "year")) %>% 
  select(avg_salary, country, year, Gender) %>% 
  filter(!country %in% c("Scotland", "Spain", "Italy", "Japan"))
```

```{r}
ggplot(graph_data, aes(x = country, y = avg_salary, fill = Gender)) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = c("cadetblue", "lightcoral")) + 
  labs(x = "Country", 
       y = "Average Annual Salary", 
       title = "Average Annual Salary in Selected Professional Soccer Leagues, 2017", 
       caption = "Data from Global Sports Salary Survey 2017 and 2018.") +
  theme_minimal() +
  theme(plot.title = element_text(hjust =0.5))
  
 
```

