---
title: "National teams worldwide"
author: "Bernadette Stadler"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(readr)

```

```{r read in data}
wws <- read_csv("raw-data/tabula-GSSS 2017.csv", col_types = cols(
  league = col_character(),
  country = col_character(),
  Season = col_character(),
  Sport = col_character(),
  Teams = col_double(),
  Players = col_double()
))%>% clean_names()

# read in womens salaries data 

mws <- suppressWarnings(read_csv("raw-data/tabula-GSSS 2017_2.csv", col_types =cols(
  RANK = col_character(),
  TEAM = col_character(),
  LEAGUE = col_character()
))) %>% drop_na() %>% filter(!LEAGUE == "LEAGUE") %>% clean_names()

# read in mens salaries data for 2017.Use suppress warnings because I got a warning 
# saying that a missing column name was filled in with X4 that I couldn't get to 
# to go away. Filter to get rid of multiple table headers from subsequent pages of 
# the document I scraped it from. 

mws_18 <- suppressWarnings(read_csv("raw-data/tabula-GSSS 2018.csv", col_types =cols(
  COUNTRY = col_character(),
  CONTINENT = col_character(),
  X4 = col_character()
))) %>% clean_names()

# read in mens salaries data for 2018.Use suppress warnings for same reason as above
```

```{r clean data}
mws2 <- mws %>% filter(league == "EPL" | league == "Bundesliga" | league == "Ligue 1" | league == "La Liga" | league == "Serie A" | league == "MLS" | league == "CSL" | league == "Scot Prem" | league == "J.League") %>%

  # filter for soccer leagues

  mutate(Country = case_when(
    league == "EPL" ~ "England",
    league == "Bundesliga" ~ "Germany",
    league == "Serie A" ~ "Italy",
    league == "Ligue 1" ~ "France",
    league == "La Liga" ~ "Spain",
    league == "MLS" ~ "USA",
    league == "CSL" ~ "China",
    league == "Scot Prem" ~ "Scotland",
    league == "J.League" ~ "Japan",
    TRUE ~ "NA"
  )) %>%
  # mutate soccer league names to be the name of the country the league plays in

  select(league, avg_annual_pay_2, Country) %>%

  # select variables of interest

  mutate(avg_annual_pay_2 = if_else(avg_annual_pay_2 == "$6,739,250($129,601)", "$6,739,250 ($129,601)", avg_annual_pay_2)) %>%

  # mutate to fix the one column where there isn't a space between the annual and weekly
  # pay

  separate(avg_annual_pay_2, into = c("annual_pay"), sep = " ", extra = "drop") %>%

  # separate out annual and weekly pay and drop weekly pay

  mutate(annual_pay = parse_number(annual_pay))

# parse the number from annual pay so that I can work with it as a number

country_number <- mws2 %>% count(Country)

# use count to collapse country names to one row per country to get the number
# of times each country appears in the tibble. I will used this to get the average
# salary per country since some countries have multiple leagues/teams listed in this
# dataset

mws3 <- country_number %>%
  right_join(mws2, by = "Country") %>%

  # join tibble listing country and number of times country appears to the data

  group_by(Country) %>%
  mutate(avg_annual_pay_country = sum(annual_pay) / n) %>%

  # calculate average annual pay by dividing the sum per country by number of times
  # the country appears

  group_by(Country, avg_annual_pay_country) %>%
  count()

# use count to collapse the data

missing_countries <- mws_18 %>% select(country, avg_basic_annual_1) %>%

  # make a missing countries table, which is where I will store the 2018 data
  # for the countries I did not have 2017 data for. I made the choice to bring in
  # 2018 data as a proxy for 2017 data because withour these countries included,
  # my sample was very small. I note this decision in the user interface of my app.

  drop_na() %>%

  # get rid of pesky NAs

  filter(country %in% c("AUSTRALIA ASIA", "MEXICO", "SWEDEN EUROPE")) %>%

  # filter for my missing countries

  mutate(Country = country) %>%
  # mutate so that country is capitalzied, which will allow me to seamlessly
  # join this tibble with the other using bind_rows

  mutate(avg_annual_pay_country = parse_number(avg_basic_annual_1)) %>%

  # make a new column with the same name as in the other tibble

  select(Country, avg_annual_pay_country)

# select variables of interest


mws4 <- mws3 %>% bind_rows(missing_countries) %>%

  # bind the rows together

  mutate(country_clean = case_when(
    Country == "AUSTRALIA ASIA" ~ "Australia",
    Country == "SWEDEN EUROPE" ~ "Sweden",
    Country == "MEXICO" ~ "Mexico",
    TRUE ~ Country
  )) %>%

  # rename variables where they looked weird

  mutate(Gender = "Men")

# make a gender column

wws2 <- wws %>% filter(sport == "Football") %>%

  # filter women's data for the right sport

  select(u_s, country) %>%

  # select salary in usd, country

  mutate(avg_salary = parse_number(u_s)) %>%

  # pull out the number from u_s so that I can use it as a number

  mutate(Gender = "Women")

# add a gender column

graph_data <- wws2 %>%
  full_join(mws4, by = c("avg_salary" = "avg_annual_pay_country", "country" = "country_clean", "Gender" = "Gender")) %>%
  
  # join women's and men's data 
  
  select(avg_salary, country, Gender) %>%
  
  # select variables of interest 
  
  filter(!country %in% c("Scotland", "Spain", "Italy", "Japan"))

  # filter out countries for which I only have data for thre women's or men's teams 
```

```{r make graph}
graph_data %>%
  
  # make a graph. This is where I will interactively filter in shiny
  
ggplot(aes(x = country, y = avg_salary, fill = Gender)) +
  
  # x axis is country, y is salary, fill is gender 
  
  geom_col(position = "dodge") +
  
  # set position to dodge so that columns display side by side 
  
  scale_fill_manual(values = c("Men" = "purple4", "Women" = "red")) + 
  
  # set colors manually 
  
  labs(x = "Country", 
       y = "Average Annual Salary", 
       title = "Average Annual Salary in Selected Professional Soccer Leagues, 2017", 
       caption = "Data from Global Sports Salary Survey 2017 and 2018.") +
  
  # relabel x and y axes, add a caption and title 
  
  theme_minimal() +
  
  # set theme 
  
  theme(plot.title = element_text(hjust =0.5))

  # center title
 
```

