---
title: "Rev_exp"
author: "Bernadette Stadler"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(janitor)
library(tidyverse)
```

```{r read in data}
rev_exp <- read_excel("raw-data/Revenue and expense data.xlsx") %>%
    clean_names()

# read in data 

```


```{r format data}
    rev <- rev_exp %>%
  
      # first, I'm just going to work with revenue data 
  
      select(fiscal_year, womens_revenue, mens_revenue) %>%
  
      # select variables of interest 
  
      pivot_longer(
        cols = ends_with("revenue"),
        names_to = "Team",
        values_to = "Revenue"
      ) %>%
  
      # pivot the data so that the USMNT/USWNT data ends up in one column 
      # this will allow me to facet wrap my graph by men and women later
   
      mutate(fiscal_year = if_else(
        fiscal_year == "2019 (projected)", 2019, suppressWarnings(as.double((fiscal_year))
      ))) %>%
  
      # mutate to remove (projected) so that I can make fiscal_year a 
      # double column. Use suppressWarnings to get rid of the NA introduced by coercion
      # warning (I couldn't figure out how to do it any other way)
  
      mutate(Team = if_else(Team == "womens_revenue", "USWNT", "USMNT"))
      
      # mutate to change womens_revenue and mens_revenue to USWNT and USMNT, 
      # which is how I want it to show up in the graph 
    
    exp <- rev_exp %>%
      
      # now work with expense data 
      
      select(fiscal_year, womens_expenses, mens_expenses) %>%
      
      # select variables of interest  
      
      pivot_longer(
        cols = ends_with("expenses"),
        names_to = "Team",
        values_to = "Expenses"
      ) %>%
      
      # pivot the data so that the USMNT/USWNT data ends up in one column 
      # this will allow me to facet wrap my graph by men and women later
      
      mutate(fiscal_year = if_else(
        fiscal_year == "2019 (projected)", 2019, suppressWarnings(as.double(fiscal_year))
      )) %>%
      
      # make 2019 (projected) into a numeric value, as well as whole column. Use
      # suppress warning for same purposes as above.
      
      mutate(Team = if_else(Team == "womens_expenses", "USWNT", "USMNT"))
    
      # mutate mens_expenses and womens_expenses to USWNT and USMNT
    
    rev_exp_formatted <- exp %>%
      left_join(rev, by = c("fiscal_year", "Team")) %>%
      
      # rejoin the data 
      
      mutate(Expenses = if_else(is.na(Expenses), 0, Expenses)) %>%
      
      # change NAs to 0 revenue so that I can collapse the rows. The NAs were
      # introduced because I have separate rows for revenue and expense 
      
      mutate(Revenue = if_else(is.na(Revenue), 0, Revenue)) %>%
      
      # change NAs to 0 in revenue so that I can add and subtract data below 
      
      mutate(Net = Revenue - Expenses) %>%
      
      # make a net column by subtracting expenses from revenue 
      
      pivot_longer(
        cols = Expenses:Net,
        names_to = "Type",
        values_to = "Amount"
      )
    
    # pivot longer so that I will be able to filter by Revenue, Expenses and Net. 
    # I'm not sure if this is by design, but this is one of the few ways I was able
    # to get reactive variables to work in shiny
    
    rev_exp_formatted$Type <- factor(rev_exp_formatted$Type , levels = c("Revenue", "Expenses", "Net"))
    
    # assign levels to Revenue, Expenses and Net so that they display with Net last 
    # instead of in alphabetical order 
    
```


```{r make graph}
    
rev_exp_formatted %>%
  # make a ggplot. This is where I will add a filter for the interactive variable in 
  # shiny 
  
  ggplot(aes(x = fiscal_year, y = Amount, fill = Type)) +
  
  # fiscal_year goes on x axis, amount on y axis, color by type 
  
  geom_col(position = "dodge") +
  
  # set columns to dodge so that they display side by side instead of stacked 
  
  scale_fill_manual(values = c(
    "Expenses" = "red", "Revenue" = "green", "Net" = "black")
    ) +
  
  # set the colors manually 
  
  facet_wrap(~Team) +
  
  # facet wrap by team 
  
  labs(
    x = "Fiscal Year",
    y = "Amount in U.S. dollars",
    title = "Annual Team Expenses and Revenue",
    caption = "Data from U.S. soccer annual reports"
  ) +
  
  # relabel x and y, add title and caption 
  
  theme_minimal() +
  
  # set theme to minimal 
  
  theme(
    plot.title = element_text(hjust = 0.5)
  )

# center title 

```

