library(shiny)
library(readr)
library(ggplot2)
library(plotly)
library(readxl)
library(janitor)
library(reshape2)
library(scales)
library(gt)
library(tidyverse)

# Define UI for application

ui <- fluidPage(
  rev_exp <- read_excel("raw-data/Revenue and expense data.xlsx") %>%
    clean_names(),

  # read in U.S. soccer revenue and expenses dataset

  wws <- read_csv("raw-data/tabula-GSSS 2017.csv", col_types = cols(
    league = col_character(),
    country = col_character(),
    Season = col_character(),
    Sport = col_character(),
    Teams = col_double(),
    Players = col_double()
  )) %>% clean_names(),

  # read in womens salaries data

  mws <- suppressWarnings(read_csv("raw-data/tabula-GSSS 2017_2.csv", col_types = cols(
    RANK = col_character(),
    TEAM = col_character(),
    LEAGUE = col_character()
  ))) %>%
    drop_na() %>%
    filter(!LEAGUE == "LEAGUE") %>%
    clean_names(),

  # read in mens salaries data for 2017.Use suppress warnings because I got a warning
  # saying that a missing column name was filled in with X4 that I couldn't get to
  # to go away. Filter to get rid of multiple table headers from subsequent pages of
  # the document I scraped it from.

  mws_18 <- suppressWarnings(read_csv("raw-data/tabula-GSSS 2018.csv", col_types = cols(
    COUNTRY = col_character(),
    CONTINENT = col_character(),
    X4 = col_character()
  ))) %>% clean_names(),

  # read in mens salaries data for 2018.Use suppress warnings for same reason as above

  bonuses <- read_excel("raw-data/World cup bonuses.xlsx") %>% clean_names(),

  # read in bonuses data (manually compiled from Guardian article)

  model_data <- read_csv("raw-data/womens-football-2019-clean.csv",
    col_types = cols(
      X1 = col_character(),
      Population = col_number(),
      `Global Gender Gap Ranking 2018` = col_character(),
      `FIFA WF Ranking 2019` = col_character(),
      `Female players playing organized football` = col_character(),
      `licesned coaches` = col_character(),
      `licensed referees` = col_character(),
      `Women's soccer strategy?` = col_character(),
      `Mixed-gender football?` = col_character()
    )
  ) %>% clean_names(),

  gdp_data <- read_csv("raw-data/GDP_data.csv",
    skip = 4,
    col_types = cols(
      .default = col_double(),
      `Country Name` = col_character(),
      `Country Code` = col_character(),
      `Indicator Name` = col_character(),
      `Indicator Code` = col_character(),
      `2019` = col_logical(),
      X65 = col_logical()
    )
  ) %>% clean_names(),

  gender_index <- read_csv("raw-data/data.csv",
    col_types = cols(
      `Country ISO3` = col_character(),
      `Country Name` = col_character(),
      `Indicator Id` = col_double(),
      Indicator = col_character(),
      `Subindicator Type` = col_character(),
      `2006` = col_double(),
      `2007` = col_double(),
      `2008` = col_double(),
      `2009` = col_double(),
      `2010` = col_double(),
      `2011` = col_double(),
      `2012` = col_double(),
      `2013` = col_double(),
      `2014` = col_double(),
      `2015` = col_double(),
      `2016` = col_double(),
      `2018` = col_double()
    )
  ) %>% clean_names(),

  navbarPage(
    "Equal Work, Equal Pay? Women's Soccer in 2019",

    tabPanel(
      "USWNT equal pay lawsuit",

      # My first panel is on the USWNT equal pay lawsuit. It will highlight
      # issues relevant to the lawsuit: USWNT and USMNT regular season
      # salaries, USWNT and USMNT World Cup bonuses, and the expenses and
      # revenue generated by each team.

      tabsetPanel(
        tabPanel("Regular Season Salaries"),
        tabPanel(
          "World Cup Bonuses",

          # make and title the panel

          br(),
          h5("How much do USWNT and USMNT players make in bonuses at each stage of the World Cup?"),
          br(),

          # add a title in the body of the app, leaving space around it for
          # aesthetic purposes

          includeHTML("www/world_cup_bonuses_tab.html"),

          # insert a table showing the amount that each team makes in
          # bonuses at each stage of the World Cup and the World Cup
          # qualifying process. I made the chart in a separate file
          # and saved it as an html object.

          br(),
          h5("How much money in bonuses would USWNT and USMNT players walk away with if they exited the world cup at the following stages?"),
          br(),
          img(src = "world_cup_bonuses.png")

          # insert a graph showing the cumulative amount that each team
          # makes per stage in the world cup. I made the graph in a separate
          # file and saved it as an image so that my app would run faster.
        ),

        tabPanel(
          "Expenses and Revenue",

          # make and title another panel

          sidebarPanel(
            checkboxGroupInput("rev_exp_net",
              "Display",
              choices = c("Revenue", "Expenses", "Net"),
              selected = c("Revenue", "Expense")
            )
          ),

          # add a sidebar panel with multiple checkboxes that the viewer can
          # click to see multiple variables showed

          mainPanel(
            h5("In response to the USWNT lawsuit, U.S. Soccer has claimed that it
               is justified in paying female atheletes less because of the market
               reality that women's soccer generates less revenue. This graph shows 
               USWNT and USMNT revenue, expesnes, and net income for fiscal year 2014
               through the projected values for 2019. While the USWNT had generated
               less income for U.S. soccer in some years, the reverse is true in 
               others."),
            plotOutput("plot1")

            # display the plot (created in the server)
          )
        )
      )
    ),
    tabPanel(
      "State of women's Soccer Worldwide",

      # create and name a second tab

      tabsetPanel(
        tabPanel(
          "National league salaries",
          h5("The question of equal (or unequal) investment in women's and 
                   men's soccer goes beyond the USWNT lawsuit. This section explores 
                   investment in men's and women's soccer at the professional level
                   throughout the world."),
          h3("World Snapshot"),
          sidebarPanel(
            checkboxGroupInput("gender", "Select",
              choices = c("Women", "Men"),
              selected = c("Women", "Men")
            ),
            "Note: Data for the men's leagues in Sweden, Australia and Mexico was not 
                   available for 2017, so I am using data from 2018 as a proxy."
          ),
          mainPanel(
            plotOutput("plot9")
          ),
          h3("USA"),
          column(
            4,
            "The American professional soccer leagues are Major League Soccer (MLS) 
                  and the National Women's Soccer League (NWSL). Many USMNT hopefuls 
                  play in the MLS, while it USWNT players are practically required 
                  to play in the NWSL. This graph shows the range of possible salaries 
                  in the NWSL and MLS for 2013-2018."
          ),
          column(
            8,
            img(src = "plot5.png")
          )
        ),
        tabPanel(
          "Model: Gender Equality and Performance",
          sidebarPanel(
            selectInput("model_input", "Independent Variable",
              choices = c(
                "gendergap_18",
                "fem_players",
                "GDP",
                "population"
              )
            )
          ),
          mainPanel(
            plotOutput("model1")
          )
        )
      )
    ),
    tabPanel(
      "About",
      h3("About this project"),
      h5("In March 2019, the 28 members of the United States Women's National 
               Soccer Team (USWNT) filed a class-actionlawsuit against their employer,
               U.S. Soccer. The lawsuit accuses U.S. soccer of violating the Equal 
               Pay Act and Title VII of thet Civil RIghts Act of 1964 by consistently 
               paying USWNT athletes less than their male counterparts (players on 
               the U.S. Men's National Team or USMNT). The lawsuit, and the subsequent
               dominance of the USWNT in the 2019 Women's World Cup, have drawn 
               significant attention to the issue of equal pay in professional soccer. 
               However, the USWNT and USMNT have different pay structures that makes 
               it difficult to compare their earnings. This project seeks to explain the 
               USWNT and USMNT compensation structures and earning potentials in a
               way that allows for useful comparisons. It will also go beyond the 
               USWNT to examine how professional female soccer players are compensated 
               throughout the world."),
      h3("Data"),
      h5("The data for this project is drawn from the Major League Soccer Player's
          Association (MLSPA), US Soccer's annual reports, and jouralistic articles 
          from the Guardian, the Equalizer, the New York Times, and the Washington 
          Post.The National Womens'Soccer League does not collect information on 
          player salaries and was unable to provide any when I contacted them. To
          date, FIFA has not responded to a request to use their data on women in 
          football."),
      h3("About Me"),
      h5("I am a first year Master's Candidate in Russian, Eastern European, and
         Central Asian Studies at Harvard University. I'm also a long-time amature
         soccer player and avid fan of women's soccer.")
    )
  )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  output$plot1 <- renderPlot({
    rev <- rev_exp %>%

      # first, I'm just going to work with revenue data

      select(fiscal_year, womens_revenue, mens_revenue) %>%

      # select variables of interest

      pivot_longer(
        cols = ends_with("revenue"),
        names_to = "Team",
        values_to = "Revenue"
      ) %>%

      # pivot the data so that the USMNT/USWNT data ends up in one column
      # this will allow me to facet wrap my graph by men and women later

      mutate(fiscal_year = if_else(
        fiscal_year == "2019 (projected)", 2019, suppressWarnings(as.double((fiscal_year)))
      )) %>%

      # mutate to remove (projected) so that I can make fiscal_year a
      # double column. Use suppressWarnings to get rid of the NA introduced by coercion
      # warning (I couldn't figure out how to do it any other way)

      mutate(Team = if_else(Team == "womens_revenue", "USWNT", "USMNT"))

    # mutate to change womens_revenue and mens_revenue to USWNT and USMNT,
    # which is how I want it to show up in the graph

    exp <- rev_exp %>%

      # now work with expense data

      select(fiscal_year, womens_expenses, mens_expenses) %>%

      # select variables of interest

      pivot_longer(
        cols = ends_with("expenses"),
        names_to = "Team",
        values_to = "Expenses"
      ) %>%

      # pivot the data so that the USMNT/USWNT data ends up in one column
      # this will allow me to facet wrap my graph by men and women later

      mutate(fiscal_year = if_else(
        fiscal_year == "2019 (projected)", 2019, suppressWarnings(as.double(fiscal_year))
      )) %>%

      # make 2019 (projected) into a numeric value, as well as whole column. Use
      # suppress warning for same purposes as above.

      mutate(Team = if_else(Team == "womens_expenses", "USWNT", "USMNT"))

    # mutate mens_expenses and womens_expenses to USWNT and USMNT

    rev_exp_formatted <- exp %>%
      left_join(rev, by = c("fiscal_year", "Team")) %>%

      # rejoin the data

      mutate(Expenses = if_else(is.na(Expenses), 0, Expenses)) %>%

      # change NAs to 0 revenue so that I can collapse the rows. The NAs were
      # introduced because I have separate rows for revenue and expense

      mutate(Revenue = if_else(is.na(Revenue), 0, Revenue)) %>%

      # change NAs to 0 in revenue so that I can add and subtract data below

      mutate(Net = Revenue - Expenses) %>%

      # make a net column by subtracting expenses from revenue

      pivot_longer(
        cols = Expenses:Net,
        names_to = "Type",
        values_to = "Amount"
      )

    # pivot longer so that I will be able to filter by Revenue, Expenses and Net.
    # I'm not sure if this is by design, but this is one of the few ways I was able
    # to get reactive variables to work in shiny

    rev_exp_formatted$Type <- factor(rev_exp_formatted$Type, levels = c("Revenue", "Expenses", "Net"))

    # assign levels to Revenue, Expenses and Net so that they display with Net last
    # instead of in alphabetical order

    rev_exp_formatted %>%
      # make a ggplot

      filter(Type %in% c(input$rev_exp_net)) %>%

      # filter for interactive variables. I use include instead of equals because
      # I allow the user to select multiple inputs here

      ggplot(aes(x = fiscal_year, y = Amount, fill = Type)) +

      # fiscal_year goes on x axis, amount on y axis, color by type

      geom_col(position = "dodge") +

      # set columns to dodge so that they display side by side instead of stacked

      scale_fill_manual(values = c(
        "Expenses" = "brown1", "Revenue" = "forestgreen", "Net" = "black"
      )) +

      # set the colors manually

      facet_wrap(~Team) +

      # facet wrap by team

      labs(
        x = "Fiscal Year",
        y = "Amount in U.S. dollars",
        title = "Annual Team Expenses and Revenue",
        caption = "Data from U.S. soccer annual reports"
      ) +

      # relabel x and y, add title and caption

      theme_minimal() +

      # set theme to minimal

      theme(
        plot.title = element_text(hjust = 0.5)
      )

    # center title
  })

  output$plot9 <- renderPlot({
    mws2 <- mws %>% filter(league == "EPL" | league == "Bundesliga" | league == "Ligue 1" | league == "La Liga" | league == "Serie A" | league == "MLS" | league == "CSL" | league == "Scot Prem" | league == "J.League") %>%

      # filter for soccer leagues

      mutate(Country = case_when(
        league == "EPL" ~ "England",
        league == "Bundesliga" ~ "Germany",
        league == "Serie A" ~ "Italy",
        league == "Ligue 1" ~ "France",
        league == "La Liga" ~ "Spain",
        league == "MLS" ~ "USA",
        league == "CSL" ~ "China",
        league == "Scot Prem" ~ "Scotland",
        league == "J.League" ~ "Japan",
        TRUE ~ "NA"
      )) %>%

      # mutate soccer league names to be the name of the country the league plays in

      select(league, avg_annual_pay_2, Country) %>%

      # select variables of interest

      mutate(avg_annual_pay_2 = if_else(avg_annual_pay_2 == "$6,739,250($129,601)", "$6,739,250 ($129,601)", avg_annual_pay_2)) %>%

      # mutate to fix the one column where there isn't a space between the annual and weekly
      # pay

      separate(avg_annual_pay_2, into = c("annual_pay"), sep = " ", extra = "drop") %>%

      # separate out annual and weekly pay and drop weekly pay

      mutate(annual_pay = parse_number(annual_pay))

    # parse the number from annual pay so that I can work with it as a number

    country_number <- mws2 %>% count(Country)

    # use count to collapse country names to one row per country to get the number
    # of times each country appears in the tibble. I will used this to get the average
    # salary per country since some countries have multiple leagues/teams listed in this
    # dataset

    mws3 <- country_number %>%
      right_join(mws2, by = "Country") %>%

      # join tibble listing country and number of times country appears to the data

      group_by(Country) %>%
      mutate(avg_annual_pay_country = sum(annual_pay) / n) %>%

      # calculate average annual pay by dividing the sum per country by number of times
      # the country appears

      group_by(Country, avg_annual_pay_country) %>%
      count()

    # use count to collapse the data

    missing_countries <- mws_18 %>% select(country, avg_basic_annual_1) %>%

      # make a missing countries table, which is where I will store the 2018 data
      # for the countries I did not have 2017 data for. I made the choice to bring in
      # 2018 data as a proxy for 2017 data because withour these countries included,
      # my sample was very small. I note this decision in the user interface of my app.

      drop_na() %>%

      # get rid of pesky NAs

      filter(country %in% c("AUSTRALIA ASIA", "MEXICO", "SWEDEN EUROPE")) %>%

      # filter for my missing countries

      mutate(Country = country) %>%
      # mutate so that country is capitalzied, which will allow me to seamlessly
      # join this tibble with the other using bind_rows

      mutate(avg_annual_pay_country = parse_number(avg_basic_annual_1)) %>%

      # make a new column with the same name as in the other tibble

      select(Country, avg_annual_pay_country)

    # select variables of interest

    mws4 <- mws3 %>% bind_rows(missing_countries) %>%

      # bind the rows together

      mutate(country_clean = case_when(
        Country == "AUSTRALIA ASIA" ~ "Australia",
        Country == "SWEDEN EUROPE" ~ "Sweden",
        Country == "MEXICO" ~ "Mexico",
        TRUE ~ Country
      )) %>%

      # rename variables where they looked weird

      mutate(Gender = "Men")

    # make a gender column

    wws2 <- wws %>% filter(sport == "Football") %>%

      # filter women's data for the right sport

      select(u_s, country) %>%

      # select salary in usd, country

      mutate(avg_salary = parse_number(u_s)) %>%

      # pull out the number from u_s so that I can use it as a number

      mutate(Gender = "Women")

    # add a gender column

    graph_data <- wws2 %>%
      full_join(mws4, by = c("avg_salary" = "avg_annual_pay_country", "country" = "country_clean", "Gender" = "Gender")) %>%

      # join women's and men's data

      select(avg_salary, country, Gender) %>%

      # select variables of interest

      filter(!country %in% c("Scotland", "Spain", "Italy", "Japan"))

    # filter out countries for which I only have data for thre women's or men's teams

    graph_data %>%

      # make a graph

      filter(Gender %in% c(input$gender)) %>%

      # filter by reactive variable

      ggplot(aes(x = country, y = avg_salary, fill = Gender)) +

      # x axis is country, y is salary, fill is gender

      geom_col(position = "dodge") +

      # set position to dodge so that columns display side by side

      scale_fill_manual(values = c("Men" = "purple4", "Women" = "red")) +

      # set colors manually

      labs(
        x = "Country",
        y = "Average Annual Salary",
        title = "Average Annual Salary in Selected Professional Soccer Leagues, 2017",
        caption = "Data from Global Sports Salary Survey 2017 and 2018."
      ) +

      # relabel x and y axes, add a caption and title

      theme_minimal() +

      # set theme

      theme(plot.title = element_text(hjust = 0.5))

    # center title
  })

  output$model1 <- renderPlot({
    model_data2 <- model_data %>%
      mutate(gendergap_18 = suppressWarnings(as.numeric((global_gender_gap_ranking_2018)))) %>%

      # mutate fifa data to change the name of global_gender_gap_ranking_2018 to something
      # easier to use and also to make it numeric. I used suppress warnings here to quiet
      # the NA introduced by coercion warning

      mutate(fifa_19 = suppressWarnings(as.numeric((fifa_wf_ranking_2019)))) %>%

      # make fifa_19, same logic as above

      mutate(fem_players = suppressWarnings(
        as.numeric((female_players_playing_organized_football))
      )) %>%

      # make fem_players, same logic as above

      select(x1, population, gendergap_18, fifa_19, fem_players) %>%

      # select variables of interest

      drop_na(gendergap_18)

    # drop NAs in gendergap_18. I didn't drop all NAs because it decimated the dataset,
    # but wanted to drop NAs from the variable that I will join by

    gdp_clean <- gdp_data %>% select(country_name, indicator_name, x2018)

    # select variables of interst in gdp data


    gender_index_clean <- gender_index %>%
      select(country_name, indicator, subindicator_type, x2018) %>%
      filter(indicator == "Overall Global Gender Gap Index" & subindicator_type == "Rank")

    # select columns and rows of interest from global gender gap data

    merge_1 <- gdp_clean %>%
      left_join(gender_index_clean, by = "country_name") %>%
      mutate(GDP = x2018.x) %>%
      mutate(gender_rank = x2018.y) %>%
      select(country_name, GDP, gender_rank)

    # join gdp and gender gap data, mutate to give year columns more intuitive names

    merge_2 <- model_data2 %>%
      left_join(merge_1, by = c("gendergap_18" = "gender_rank")) %>%

      # join merged data above with fifa data

      mutate(GDP = log10(GDP)) %>%
      mutate(population = log10(population)) %>%

      # take log of GDP and population so the graph won't look so crazy

      select(fifa_19, population, gendergap_18, fem_players, GDP) %>%

      # select variables of interest

      pivot_longer(cols = population:GDP, names_to = "Type2", values_to = "value")

    # pivot longer so that I will be able to filter by type in the next step

    merge_2 %>%
      filter(Type2 == input$model_input) %>%

      # filter by interactive variable

      ggplot(aes(x = value, y = fifa_19)) +

      # make graph

      geom_point() +
      geom_smooth(formula = y ~ x, method = "lm")

    # add scatterplot and regression layers
  })
}

# Run the application
shinyApp(ui = ui, server = server)